# 공통
server:
  port: 8080
spring:
  profiles:
    active: "local"
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    activate:
      on-profile: "local"
todak:
  cors:
    allowed-origin: ${ALLOWED_LOCAL_ORIGIN}
---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
todak:
  cors:
    allowed-origin: "http://localhost:1234"