# 공통
server:
  port: 8080
spring:
  profiles:
    active: "local"
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: "local"
---
spring:
  config:
    activate:
      on-profile: "test"
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
ai:
  server:
    url:
      domain: "test-ai-server-url-domain"