# 공통
server:
  port: 8080
spring:
  profiles:
    active: "local"
jwt:
  secret-key: ${JWT_SECRET_KEY:abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl}
  access-expire-time: ${ACCESS_EXPIRE_TIME:3600000}
  refresh-expire-time: ${REFRESH_EXPIRE_TIME:604800000}
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: "local"
todak:
  cors:
    allowed-origin: ${ALLOWED_LOCAL_ORIGIN}
ai:
  server:
    url:
      domain: ${AI_SERVER_URL_DOMAIN}
---
spring:
  config:
    activate:
      on-profile: "test"
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
todak:
  cors:
    allowed-origin: "http://localhost:1234"
ai:
  server:
    url:
      domain: "test-ai-server-url-domain"