name: Spring Boot Build and Test

on:
  pull_request:
    branches: [main, release, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "21"

      # - name: Set up environment variables
      #   run: |
      #     echo "${{ secrets.SPRING_ENV }}" > .env
      #     while IFS= read -r line; do
      #       echo "$line" >> $GITHUB_ENV
      #     done < .env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
        # env:
        #   SPRING_CONFIG_ADDITIONAL_LOCATION: file:.env[.properties]

      - name: Discord 알림
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "NextJS 빌드 결과"
          description: |
            ${{ job.status != 'success' && format('실패 단계: {0}', job.status) || '' }}
          color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
