#reuse workflow

name: Reuse Build and Publish to GHCR

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build-and-publish:
    uses: kakaotech-19/.github/.github/workflows/build-and-publish-ghcr.yml@main
    secrets: inherit
  
  dispatch-cd:
    needs: build-and-publish
    uses: kakaotech-19/.github/.github/workflows/dispatch-cd.yaml@main
    secrets: inherit
