#reuse workflow

name: Reuse Build and Publish to GHCR

on:
  push:
    branches: [ main, release, develop ]
  pull_request:

jobs:
  build-and-publish:
    uses: kakaotech-19/.github/.github/workflows/build-and-publish-ghcr.yml@main
    secrets: inherit