name: spring build

on:
  pull_request:
    branches: [main, release, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "21"

      - name: Gradle 권한설정
        run: chmod +x gradlew

      - name: Gradle 빌드
        run: ./gradlew clean build
