name: Sync GitHub issue to Jira

on:
  issues:
    types: [opened, reopened, closed, edited]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
      # Jira 로그인
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # Github issue - Jira 동기화
      - name: Create Jira issue
        if: github.event.action == 'opened'
        uses: atlassian/gajira-create@v3
        with:
          project: KAN
          issuetype: Task
          summary: "[GitHub #${{ github.event.issue.number }}] ${{ github.event.issue.title }}"
          description: |
            GitHub Issue Link: ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}

      - name: Update Jira issue
        if: github.event.action == 'edited'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "In Progress"

      - name: Close Jira issue
        if: github.event.action == 'closed'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "Done"