name: Issue to Jira

# 이슈 작업시 발동
on:
  issues:
    types: [opened, reopened, closed, edited]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
      # 로그인
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      # Jira issue 확인(이슈 생성 이외의 작업에 필요)
      - name: Find Jira issue
        id: find
        uses: atlassian/gajira-find@v3
        with:
          jql: 'summary ~ "[GitHub #${{ github.event.issue.number }}]"'

      # Jira issue 생성
      - name: Create Jira issue
        id: create
        if: steps.find.outputs.issues == ''
        uses: atlassian/gajira-create@v3
        with:
          project: KAN
          issuetype: Task
          summary: "[GitHub #${{ github.event.issue.number }}] ${{ github.event.issue.title }}"
          description: |
            GitHub Issue Link: ${{ github.event.issue.html_url }}
            ${{ github.event.issue.body }}

      # Issue 설정(하단 작업에 필요)
      - name: Set Jira issue key
        run: |
          if [ "${{ steps.find.outputs.issues }}" != "" ]; then
            echo "ISSUE_KEY=${{ steps.find.outputs.issues }}" >> $GITHUB_ENV
          elif [ "${{ steps.create.outputs.issue }}" != "" ]; then
            echo "ISSUE_KEY=${{ steps.create.outputs.issue }}" >> $GITHUB_ENV
          else
            echo "No Jira issue found or created."
            exit 1
          fi

      # Jira Issue 수정
      - name: Update Jira issue
        if: github.event.action == 'edited'
        uses: atlassian/gajira-update@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          summary: "[GitHub #${{ github.event.issue.number }}] ${{ github.event.issue.title }}"
          description: |
            GitHub Issue Link: ${{ github.event.issue.html_url }}
            ${{ github.event.issue.body }}

      # Github Issue 수정시 Jira Issue의 상태를 In Progress로 설정
      - name: Transition Jira issue to In Progress
        if: github.event.action == 'edited'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          transition: "Progress"

      # Issue 재지정
      - name: Reopen Jira issue
        if: github.event.action == 'reopened'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          transition: "Reopen"

      # Issue 완료
      - name: Close Jira issue
        if: github.event.action == 'closed'
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          transition: "Clear"
